situacao_mapping = {
    '01': 'NULA',
    '02': 'ATIVA',
    '03': 'SUSPENSA',
    '04': 'INAPTA',
    '08': 'BAIXADA'
}

company_size = {
    '00': 'NAO INFORMADO',
    '01': 'MICRO EMPRESA',
    '03': 'EMPRESA DE PEQUENO PORTE',
    '05': 'DEMAIS',
}

matriz_filial_mapping = {
    '1': 'MATRIZ',
    '2': 'FILIAL'
}

cadastral_situation_description_mapping = {
    '01': 'EXTINÇÃO POR ENCERRAMENTO LIQUIDAÇÃO VOLUNTÁRIA',
    '02': 'INCORPORAÇÃO',
    '03': 'FUSÃO',
    '04': 'CISÃO TOTAL ',
    '05': 'ENCERRAMENTO DA FALÊNCIA',
    '06': 'ENCERRAMENTO DA LIQUIDAÇÃO',
    '07': 'ELEVAÇÃO A MATRIZ',
    '08': 'TRANSPASSE ',
    '09': 'NÃO INÍCIO DE ATIVIDADE',
    '10': 'EXTINÇÃO PELO ENCERRAMENTO DA LIQUIDAÇÃO JUDICIAL',
    '11': 'ANULAÇÃO POR MULTICIPLIDADE',
    '12': 'ANULAÇÃO ONLINE DE OFICIO',
    '13': 'OMISSA CONTUMAZ',
    '14': 'OMISSA NÃO LOCALIZADA',
    '15': 'INEXISTENTE DE FATO',
    '16': 'ANULAÇÃO POR VÍCIOS',
    '17': 'BAIXA INICIADA E AINDA NÃO DEFERIDA',
    '18': 'INTERRUPÇÃO TEMPORÁRIA DAS ATIVIDADES',
    '19': 'OMISSO DE DIRPJ ATÉ 5 EXERCÍCIOS',
    '20': 'EM CONDIÇÃO DE INAPTIDÃO',
    '21': 'PEDIDO DE BAIXA INDEFERIDA',
    '22': 'RESTABELECIMENTO COM CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA',
    '23': 'COM PENDÊNCIA FISCAL',
    '24': 'POR EMISSÃO CERTIDÃO NEGATIVA',
    '25': 'CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA',
    '26': 'IRREGULARIDADE DE PAGAMENTO',
    '27': 'IRREGULARIDADE DE RECOLHIMENTO E EXIGIBILIDADE SUSPENSA',
    '28': 'TRANSFERÊNCIA FILIAL CONDIÇÃO MATRIZ',
    '29': 'AGUARDANDO CONF. DE DIRPJ/DIPJ',
    '30': 'ANR - AGUARDANDO CONF. DE DIRPJ/DIPJ',
    '31': 'EXTINÇÃO DA FILIAL',
    '32': 'INEXISTENTE DE FATO \x96 ADE/COSAR',
    '33': 'TRANSFERÊNCIA DO ÓRGÃO LOCAL A CONDIÇÃO DE FILIAL DO ÓRGÃO REGIONAL',
    '34': 'ANULAÇÃO DE INSCRIÇÃO INDEVIDA',
    '35': 'EMPRESA ESTRANGEIRA AGUARDANDO DOCUMENTAÇÃO',
    '36': 'PRÁTICA IRREGULAR DE OPERAÇÃO DE COMERCIO EXTERIOR',
    '37': 'BAIXA DE PRODUTOR RURAL',
    '38': 'BAIXA DEFERIDA PELA RFB AGUARDANDO ANALISE DO CONVENENTE',
    '39': 'BAIXA DEFERIDA PELA RFB E INDEFERIDA PELO CONVENENTE',
    '40': 'BAIXA INDEFERIDA PELA RFB E AGUARDANDO ANALISE DO CONVENENTE',
    '41': 'BAIXA INDEFERIDA PELA RFB E DEFERIDA PELO CONVENENTE',
    '42': 'BAIXA INDEFERIDA PELA RFB E SEFIN, AGUARDANDO ANALISE SEFAZ',
    '43': 'BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN',
    '44': 'BAIXA DEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE SEFIN',
    '45': 'BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFIN E INDEFERIDA PELA SEFAZ',
    '46': 'BAIXA DEFERIDA PELA RFB E SEFAZ E INDEFERIDA PELA SEFIN',
    '47': 'BAIXA DEFERIDA PELA RFB E SEFIN E INDEFERIDA PELA SEFAZ',
    '48': 'BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE SEFAZ E DEFERIDA PELA SEFIN',
    '49': 'BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN',
    '50': 'BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E AGUARDANDO ANALISE DA SEFIN',
    '51': 'BAIXA INDEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE DA SEFIN',
    '52': 'BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E INDEFERIDA PELA SEFIN',
    '53': 'BAIXA INDEFERIDA PELA RFB E SEFAZ E DEFERIDA PELA SEFIN',
    '54': 'BAIXA - TRATAMENTO DIFERENCIADO DADO AS ME E EPP (LEI COMPLEMENTAR NUMERO 123/2006)',
    '55': 'DEFERIDO PELO CONVENENTE, AGUARDANDO ANALISE DA RFB',
    '60': 'ARTIGO 30, VI, DA IN 748/2007',
    '61': 'INDICIO INTERPOS. FRAUDULENTA',
    '62': 'FALTA DE PLURALIDADE DE SOCIOS',
    '63': 'OMISSÃO DE DECLARAÇÕES',
    '64': 'LOCALIZAÇÃO DESCONHECIDA',
    '66': 'INAPTIDÃO',
    '67': 'REGISTRO CANCELADO',
    '70': 'ANULAÇÃO POR NÃO CONFIRMADO ATO DE REGISTRO DO MEI NA JUNTA COMERCIAL',
    '71': 'INAPTIDÃO (LEI 11.941/2009 ART.54)',
    '72': 'DETERMINAÇÃO JUDICIAL',
    '73': 'OMISSÃO CONTUMAZ',
    '74': 'INCONSISTÊNCIA CADASTRAL',
    '80': 'BAIXA REGISTRADA NA JUNTA, INDEFERIDA NA RFB'
}

tipo_socio_mapping = {
    '1': 'PESSOA JURÍDICA',
    '2': 'PESSOA FISICA',
    '3': 'ESTRANGEIRO'
}

natureza_mapping = {
    '1015': 'Órgão Público do Poder Executivo Federal',
    '1023': 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal',
    '1031': 'Órgão Público do Poder Executivo Municipal',
    '1040': 'Órgão Público do Poder Legislativo Federal',
    '1058': 'Órgão Público do Poder Legislativo Estadual ou do Distrito Federal',
    '1066': 'Órgão Público do Poder Legislativo Municipal',
    '1074': 'Órgão Público do Poder Judiciário Federal ',
    '1082': 'Órgão Público do Poder Judiciário Estadual',
    '1104': 'Autarquia Federal',
    '1112': 'Autarquia Estadual ou do Distrito Federal',
    '1120': 'Autarquia Municipal ',
    '1139': 'Fundação Pública de Direito Público Federal',
    '1147': 'Fundação Pública de Direito Público Estadual ou do Distrito Federal',
    '1155': 'Fundação Pública de Direito Público Municipal',
    '1163': 'Órgão Público Autônomo Federal',
    '1171': 'Órgão Público Autônomo Estadual ou do Distrito Federal',
    '1180': 'Órgão Público Autônomo Municipal',
    '1198': 'Comissão Polinacional',
    '1210': 'Consórcio Público de Direito Público (Associação Pública)',
    '1228': 'Consórcio Público de Direito Privado',
    '1236': 'Estado ou Distrito Federal',
    '1244': 'Município',
    '1252': 'Fundação Pública de Direito Privado Federal',
    '1260': 'Fundação Pública de Direito Privado Estadual ou do Distrito Federal',
    '1279': 'Fundação Pública de Direito Privado Municipal',
    '1287': 'Fundo Público da Administração Indireta Federal',
    '1295': 'Fundo Público da Administração Indireta Estadual ou do Distrito Federal',
    '1309': 'Fundo Público da Administração Indireta Municipal',
    '1317': 'Fundo Público da Administração Direta Federal',
    '1325': 'Fundo Público da Administração Direta Estadual ou do Distrito Federal',
    '1333': 'Fundo Público da Administração Direta Municipal',
    '1341': 'União',
    '2011': 'Empresa Pública',
    '2038': 'Sociedade de Economia Mista',
    '2046': 'Sociedade Anônima Aberta',
    '2054': 'Sociedade Anônima Fechada',
    '2062': 'Sociedade Empresária Limitada',
    '2070': 'Sociedade Empresária em Nome Coletivo',
    '2089': 'Sociedade Empresária em Comandita Simples',
    '2097': 'Sociedade Empresária em Comandita por Ações',
    '2127': 'Sociedade em Conta de Participação',
    '2135': 'Empresário (Individual)',
    '2143': 'Cooperativa',
    '2151': 'Consórcio de Sociedades',
    '2160': 'Grupo de Sociedades',
    '2178': 'Estabelecimento, no Brasil, de Sociedade Estrangeira',
    '2194': 'Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira',
    '2216': 'Empresa Domiciliada no Exterior',
    '2224': 'Clube/Fundo de Investimento',
    '2232': 'Sociedade Simples Pura',
    '2240': 'Sociedade Simples Limitada',
    '2259': 'Sociedade Simples em Nome Coletivo',
    '2267': 'Sociedade Simples em Comandita Simples',
    '2275': 'Empresa Binacional',
    '2283': 'Consórcio de Empregadores',
    '2291': 'Consórcio Simples',
    '2305': 'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)',
    '2313': 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)',
    '2321': 'Sociedade Unipessoal de Advogados',
    '2330': 'Cooperativas de Consumo',
    '3034': 'Serviço Notarial e Registral (Cartório)',
    '3069': 'Fundação Privada',
    '3077': 'Serviço Social Autônomo',
    '3085': 'Condomínio Edilício',
    '3107': 'Comissão de Conciliação Prévia',
    '3115': 'Entidade de Mediação e Arbitragem',
    '3131': 'Entidade Sindical',
    '3204': 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras',
    '3212': 'Fundação ou Associação Domiciliada no Exterior',
    '3220': 'Organização Religiosa ',
    '3239': 'Comunidade Indígena ',
    '3247': 'Fundo Privado ',
    '3255': 'Órgão de Direção Nacional de Partido Político',
    '3263': 'Órgão de Direção Regional de Partido Político',
    '3271': 'Órgão de Direção Local de Partido Político',
    '3280': 'Comitê Financeiro de Partido Político',
    '3298': 'Frente Plebiscitária ou Referendária',
    '3301': 'Organização Social (OS)',
    '3310': 'Demais Condomínios',
    '3999': 'Associação Privada',
    '4014': 'Empresa Individual Imobiliária',
    '4022': 'Segurado Especial',
    '4081': 'Contribuinte individual',
    '4090': 'Candidato a Cargo Político Eletivo',
    '4111': 'Leiloeiro ',
    '4120': 'Produtor Rural (Pessoa Física)',
    '5010': 'Organização Internacional',
    '5029': 'Representação Diplomática Estrangeira',
    '5037': 'Outras Instituições Extraterritoriais'
}
